version: '3'

services:

    laravel-app:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - laravel-app-volume:/var/www/html
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mindflowdb.cb8kowws2br7.us-east-1.rds.amazonaws.com
            DB_PORT: 3306
            DB_DATABASE: mindflow
            DB_USERNAME: admin
            DB_PASSWORD: proyectomindflow    
        networks:
            - default

    react-app:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - laravel-app
        ports:
            - "3000:80"
        volumes:
            - react-app-volume:/usr/src/app
        networks:
            - default
        stdin_open: true
        tty: true

networks:
    default:

volumes:
    laravel-app-volume:
    react-app-volume:
