version: '3'

services:

    laravel-app:
        restart: always
        build:
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - mysql
        volumes:
            - laravel-app-volume:/path/to/laravel/app
        links:
            - mysql
        networks:
            - default

    react-app:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - laravel-app
        ports:
            - "80:80"
        volumes:
            - react-app-volume:/path/to/react/app
        links:
            - laravel-app
        networks:
            - default
        stdin_open: true
        tty: true

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: PasswordRoot
            MYSQL_DATABASE: mindflow
        volumes:
            - mysql-volume:/var/lib/mysql
        networks:
            - default

networks:
    default:

volumes:
    laravel-app-volume:
    react-app-volume:
    mysql-volume:
