version: '3'

services:

    laravel-app:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - mysql
        volumes:
            - laravel-app-volume:/var/www/html

        networks:
            - default

    react-app:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - laravel-app
        ports:
            - "80:80"
        volumes:
            - react-app-volume:/usr/src/app
        networks:
            - default
        stdin_open: true
        tty: true
    mysql: 
        container_name: mysql
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: PasswordRoot
        volumes:
            - mysql-volume:/var/lib/mysql
        networks:
                - default
networks:
    default:

volumes:
    laravel-app-volume:
    react-app-volume:
    mysql-volume:
